n = int(input("Digite um número para ver sua tabuada: "))
n2 = 2 * n
n3 = 3 * n
n4 = 4 * n
n5 = 5 * n
n6 = 6 * n
n7 = 7 * n
n8 = 8 * n
n9 = 9 * n
n10 = 10 * n

print ("1 x {} = {}".format(n, n))
print ("2 x {} = {}".format(n, n2))
print ("3 x {} = {}".format(n, n3))
print ("4 x {} = {}".format(n, n4))
print ("5 x {} = {}".format(n, n5))
print ("6 x {} = {}".format(n, n6))
print ("7 x {} = {}".format(n, n7))
print ("8 x {} = {}".format(n, n8))
print ("9 x {} = {}".format(n, n9))
print ("10 x {} = {}".format(n, n10))
